[features]
seeds = false
skip-lint = false
[programs.localnet]
hola_test = "9yYQx48mQ2AR54yCVhuPkePSghykpw87ZJCJWHkwthqF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/chuo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
